{% set name = "argparse-manpage" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe0c09cbfed0d185b3d65828977c4a83cc5f5a7d19dccc81800acebd67d41f12

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - argparse-manpage = build_manpages.cli:main

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
  run:
    - python >=2.7

test:
  imports:
    - build_manpages
    - build_manpages.cli
  commands:
    - argparse-manpage --help

about:
  home: https://github.com/praiskup/argparse-manpage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Build manual page from python's ArgumentParser object.

extra:
  recipe-maintainers:
    - duncanmmacleod
