{% set name = "argparse-manpage" %}
{% set version = "1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2ef0c32a6ee02d7ea0605d73075ce562ac791cc386cf9060bd40166dcfc9a6a7
  patches:
    # remove script, we handle it as an entry_point here
    - no-scripts.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - argparse-manpage = build_manpages.cli:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - build_manpages
    - build_manpages.cli
  commands:
    - argparse-manpage --help

about:
  home: "https://github.com/praiskup/argparse-manpage"
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: "LICENSE"
  summary: "Build manual page from python's ArgumentParser object."

extra:
  recipe-maintainers:
    - duncanmmacleod
