{% set name = "argparse-manpage" %}
{% set version = "2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 565c76776092b3aed59e3d0806c39545dca3b910b455834fafec3b25948cf5fd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - argparse-manpage = build_manpages.cli:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - build_manpages
    - build_manpages.cli
  commands:
    - argparse-manpage --help

about:
  home: https://github.com/praiskup/argparse-manpage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Build manual page from python's ArgumentParser object.

extra:
  recipe-maintainers:
    - duncanmmacleod
