{% set name = "argparse-manpage" %}
{% set version = "4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01f289406b1461bfcef20c25623512c62d8df50b3155e76eb0d732d44ea19c0e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - argparse-manpage = argparse_manpage.cli:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - argparse_manpage
    - build_manpages
  commands:
    # check metadata
    - python -m pip check argparse-manpage
    - python -m pip show argparse-manpage
    # check entry points
    - argparse-manpage --help

about:
  home: https://github.com/praiskup/argparse-manpage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Build manual page from python's ArgumentParser object.

extra:
  recipe-maintainers:
    - duncanmmacleod
